name: Build and publish new version

on:
   release:
      types: [published]

jobs:
      build:
         runs-on: ubuntu-latest
         environment:
            name: pypi
            url: https://pypi.org/p/pyradise
         permissions:
            id-token: write

         steps:
            - uses: actions/checkout@v3

            - name: Setup Python 3.8
              uses: actions/setup-python@v4
              with:
                 python-version: 3.8

            - name: Install dependencies
              run: |
                 python -m pip install --upgrade pip
                 pip install build
                 pip install -r requirements.txt

            - name: Build package
              run: |
                 python -m build

            - name: Publish package
              uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
              with:
                 user: __token__
                 password: ${{ secrets.PYPI_API_TOKEN }}